image: 
  - Visual Studio 2017

configuration:
  - Release

environment:
  matrix:
    - solution: rapid_string.sln

install:
  - git submodule update --init --recursive

before_build:
- mkdir build 
- cd build
- cmake .. -G "Visual Studio 15 2017 Win64"

test_script:
- .\test\rapid_string_test.exe
