image: 
  - Visual Studio 2017

configuration:
  - Release

environment:
  solution: C:\Projects\rapid-string\build\rapid_string.sln
  additional_flags: "/permissive- /std:c++latest /utf-8"

install:
  - git submodule update --init --recursive

before_build:
- mkdir build 
- cd build
- cmake .. -G "Visual Studio 15 2017 Win64"

test_script:
- .\test\rapid_string_test.exe
