image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  GENERATOR: "Visual Studio 15 2017 Win64"

build:
  project: C:\Projects\rapidstring\build\rapidstring.sln

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake .. -G %GENERATOR% -Werror=dev -DCMAKE_BUILD_TYPE=%CONFIGURATION%

test_script:
  - cd C:\Projects\rapidstring\build\test\%CONFIGURATION%
  - .\rapidstring_test.exe
